FROM phelger/smp:latest

#run the image with a -v shared_jre_volume:/jre_home
ENV TOOP_DIR=/toop-dir \
  JAVA_OPTS="-Dsmp.webapp.properties.path=$TOOP_DIR/smp/config/webapp.properties -Dsmp.server.properties.path=$TOOP_DIR/smp/config/smp-server.properties -Dpd.client.properties.path=$TOOP_DIR/smp/config/pd-client.properties"

COPY default-* /

RUN  mkdir -p $TOOP_DIR/smp/config \
  && cp /default-pd-client.properties  $TOOP_DIR/smp/config/pd-client.properties \
  && cp /default-smp-server.properties $TOOP_DIR/smp/config/smp-server.properties \
  && cp /default-webapp.properties     $TOOP_DIR/smp/config/webapp.properties
  